version: "3.9"

networks:
  web:
    driver: bridge

services:

  proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - pokedex
      - sharky
      - join
      - contact-api
    networks:
      - web

  pokedex:
    build: ./pokedex
    networks:
      - web

  sharky:
    build: ./sharky
    networks:
      - web

  join:
    build: ./join
    networks:
      - web

  contact-api:
    build: ./contact-api
    environment:
      - PORT=3000
    networks:
      - web
