version: "3.9"

networks:
  web:
    driver: bridge

services:
  proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/certs:/etc/nginx/certs:ro   # <--- mountet deinen lokalen certs-Ordner
      - ./proxy/site.conf:/etc/nginx/conf.d/site.conf:ro
    depends_on:
      - portfolio
      - pokedex
      - sharky
      - join
      - contact-api
    networks:
      - web

  portfolio:
    build: ./portfolio
    networks:
      - web

  pokedex:
    build: ./pokedex
    networks:
      - web

  sharky:
    build: ./sharky
    networks:
      - web

  join:
    build: ./join
    networks:
      - web

  contact-api:
    build: ./contact-api
    environment:
      - PORT=3000
    networks:
      - web
